### ISSUE TITLE
Seggs

### ISSUE THREAD

**Issue by Taiga74164** [Dumbfuckery-Inc/Laudiolin#1]
UWOOOAAAAHHH SEEEEEXXXX!!!! UWAAAAAAHHHHHH!!!! SEEEEEEEEXXXX!!!! ORE WA SEKKUSU SURUN JANE!!!! ORE GA, ORE JISHIN GA SHINRO SEKKUSU NI NARUN JA!!!! SEEEEEEEEEXXXX!!!!!! YAMERO, TAKESHI OMAE! KONO IJOU WA TAIRYOKU GA MOTANAI! IYE!!! ORE WA SEKKUSU NI NARU ZETTAINI SEKKUSU NI NARUN DAAAA!!! SEEEEEEEEXXXXX!!!!!! SEEEEEEEEEEEXXX!!!! YAMERU!! SHINJIMAU TO TAKESHI OMAE INOCHI GA IKITE MO TSUGITA SEKKUSU DEKIRU NARO GA!!! URUSEE!!!! ORE WA SHINDA TE SEKKUSU SURUN DA!!! UWWWOOOOOO!! SEEEEEEEEEEEX!!!!!!!!!!

**Comment by Shichiha** [comment]
no segs for u

**Comment by Shichiha** [comment]
only magix

**Comment by lunaticwhat** [comment]
UWOOOAAAAHHH SEEEEEXXXX!!!! UWAAAAAAHHHHHH!!!! SEEEEEEEEXXXX!!!! ORE WA SEKKUSU SURUN JANE!!!! ORE GA, ORE JISHIN GA SHINRO SEKKUSU NI NARUN JA!!!! SEEEEEEEEEXXXX!!!!!! YAMERO, TAKESHI OMAE! KONO IJOU WA TAIRYOKU GA MOTANAI! IYE!!! ORE WA SEKKUSU NI NARU ZETTAINI SEKKUSU NI NARUN DAAAA!!! SEEEEEEEEXXXXX!!!!!! SEEEEEEEEEEEXXX!!!! YAMERU!! SHINJIMAU TO TAKESHI OMAE INOCHI GA IKITE MO TSUGITA SEKKUSU DEKIRU NARO GA!!! URUSEE!!!! ORE WA SHINDA TE SEKKUSU SURUN DA!!! UWWWOOOOOO!! SEEEEEEEEEEEX!!!!!!!!!!

**Comment by Arikatsu** [comment]
SEGGGGGS

**Comment by GanyusRightThigh** [comment]
SEEEEEEEEEEEEEX!!!!!!!!!!!!!!!!!!!
