### ISSUE TITLE
Playlists adding the first song over and over when trying to add new ones

### ISSUE THREAD

**Issue by ghost** [Dumbfuckery-Inc/Laudiolin#10]
When adding new songs to a playlist that already has a song, it'll re-add the same song over and over.

https://user-images.githubusercontent.com/111808276/229544598-293537d0-1016-4ff2-bb67-9ba43e39b554.mp4

**Comment by ghost** [comment]
After testing, the problem persists even after restarts. 
Add song, restart, add another song -> still the same song

**Comment by Arikatsu** [comment]
Just gotta add a check for it, oops.

**Comment by Arikatsu** [comment]
also fixed in 2df655c6144e66bb22c852480026b5cc1ad57176
