### ISSUE TITLE
Importing large playlist silently fails

### ISSUE THREAD

**Issue by YutaNashi** [Dumbfuckery-Inc/Laudiolin#11]
Importing a large spotify playlist (~1100 songs) silently fails. The importing alert shows and then disappears, waiting for 15-20 minutes produces no playlist and there isn't any info in the debug console. Importing a smaller spotify playlist (~100 songs) succeeds without issue almost immediately.
I tried with a latest self-built as debug to check console, the same result happened in the latest release version.

Is there a soft limit somewhere or a size issue?

**Comment by KingRainbow44** [comment]
this is most definitely a [backend issue](https://github.com/seiKiMo-Inc/Laudiolin-Backend) and probably an issue with a Spotify rate limit or some sort. won't know if it'll be fixed as its more of a third-party issue, but a potential soft-cap might be added

**Comment by YutaNashi** [comment]
Alright, thanks! I'll try to break the playlist into smaller ones.
