### ISSUE TITLE
Cannot delete playlist

### ISSUE THREAD

**Issue by chiqors** [Dumbfuckery-Inc/Laudiolin#15]
There some issue when i try to delete the playlist. It didn't do anything. Can you track this issue?
![image](https://github.com/seiKiMo-Inc/Laudiolin/assets/13832788/978352a4-cb30-4223-b47d-b51f747444e8)

**Comment by chiqors** [comment]
it turns out, it didn't call any API for delete the playlist
![image](https://github.com/seiKiMo-Inc/Laudiolin/assets/13832788/8a843c56-c872-4973-b02b-be4b2bbbe599)

**Comment by KingRainbow44** [comment]
The backend was likely down, or your playlist wasn't created at all.
