### ISSUE TITLE
Empty audio result

### ISSUE THREAD

**Issue by vewaclub** [Dumbfuckery-Inc/Laudiolin#7]
When I search for something that cannot be found (like Spotify song link), the result is an empty audio file that is 23 hours, 59 minutes, and 59 seconds long. This audio has no picture or title. I suggest adding a "Results not found" message.

![изображение](https://user-images.githubusercontent.com/72296110/222952463-78228661-767a-4204-91c5-529f3839614b.png)

**Comment by vewaclub** [comment]
![изображение](https://user-images.githubusercontent.com/72296110/222952542-ddde83df-ec67-4975-a74d-d249cdaae6f9.png)

**Comment by Arikatsu** [comment]
Hi! Thanks for letting us know about the issue. I'll fix it in the next commit tomorrow.

**Comment by Arikatsu** [comment]
This is fixed in commit ba9e95c
