### ISSUE TITLE
Download does nothing

### ISSUE THREAD

**Issue by zenitogr** [Dumbfuckery-Inc/Laudiolin#8]
When I click on download it does nothing
no notification
it isnt in the downloads "tab"

how to debug this?

i got 2.1.0 on windows 11

Edition	Windows 11 Pro
Version	22H2
Installed on	‎1/‎2/‎2023
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

**Comment by KingRainbow44** [comment]
download on what? you can download many things, tracks, playlists, everything.

**Comment by zenitogr** [comment]
on a song! I press the three dots and download track!

**Comment by zenitogr** [comment]
do you want me to build with debug and give you any errors I get?

**Comment by KingRainbow44** [comment]
stale issue, will now be closing
