### ISSUE TITLE
Playlists don't update when removing songs

### ISSUE THREAD

**Issue by ghost** [Dumbfuckery-Inc/Laudiolin#9]
When removing a song from a playlist, it doesn't update the view.

https://user-images.githubusercontent.com/111808276/229543574-e63f0e68-600e-4456-ba75-0041a846a1f1.mp4

**Comment by Arikatsu** [comment]
Can you remove a song and reload the app with ctrl + r, and see if that removes the song. I have a feeling it might be because it doesn't update the playlists content variable.

**Comment by ghost** [comment]
ctrl + r puts me back in the home screen, but yes, it does remove the song

https://user-images.githubusercontent.com/111808276/229551957-d3ac514c-b6bd-411b-8e82-3a5f415a1d72.mp4

**Comment by Arikatsu** [comment]
Okay yeah that proves my theory. Will fix after I wake up

**Comment by ghost** [comment]
gotcha! thanks

**Comment by Arikatsu** [comment]
Fixed in 4a7b827c0e6ac319f7e8f30a0be06db116442c36
